-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 8e0d7bab601ce6a8775ea98082938e60fc80eb7f
    hooks:
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: check-json
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: debug-statements
    -   id: check-docstring-first
    -   id: flake8
        args:
        - --isolated
    -   id: name-tests-test
    -   id: requirements-txt-fixer
-   repo: git://github.com/asottile/reorder_python_imports
    sha: v0.3.0
    hooks:
    -   id: reorder-python-imports
-   repo: git://github.com/pre-commit/mirrors-yapf
    sha: v0.11.1
    hooks:
    -   id: yapf
        args:
        - --diff
        - --no-local-style
-   repo: git://github.com/pre-commit/mirrors-pylint
    sha: v1.6.4
    hooks:
    -   id: pylint
        args:
        - --confidence=HIGH,INFERENCE
        - --disable=missing-docstring
        - --generated-members=objects
        - --reports=n
