# Generated by Django 4.1.7 on 2023-04-17 15:04

from django.db import migrations


def forwards(apps, schema_editor):
    # CentreModel and OrganisationModel are types, therefore CamelCase
    CentreModel = apps.get_model("centre_registry", "Centre")
    OrganisationModel = apps.get_model("centre_registry", "Organisation")
    for centre_object in CentreModel.objects.all():
        organisation_name = centre_object.organisation_name
        institution = centre_object.institution
        working_unit = centre_object.working_unit
        address = centre_object.address
        postal_code = centre_object.postal_code
        city = centre_object.city
        latitude = centre_object.latitude
        longitude = centre_object.longitude

        organisation_object = OrganisationModel.objects.create(organisation_name=organisation_name,
                                                               institution=institution,
                                                               working_unit=working_unit,
                                                               address=address,
                                                               postal_code=postal_code,
                                                               city=city,
                                                               latitude=latitude,
                                                               longitude=longitude)
        organisation_object.save()

        organisation_fk = organisation_object
        centre_object.organisation_fk = organisation_fk
        centre_object.save()





class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0033_organisation_centre_organisation_fk'),
    ]

    operations = [
        migrations.RunPython(forwards)
    ]
