# Generated by Django 2.2.8 on 2019-12-16 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centre',
            name='consortium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='centre_registry.Consortium'),
        ),
    ]
