# Generated by Django 2.2.8 on 2019-12-18 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0003_auto_20191218_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAIPMHEndpointSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centre_registry.Centre')),
                ('oaipmh_endpoints', models.ManyToManyField(to='centre_registry.OAIPMHEndpoint', verbose_name='OAI-PMH endpoints')),
                ('note', models.CharField(blank=True, max_length=1024, verbose_name='Additional note')),
            ],
        ),
    ]
