# Generated by Django 2.2.8 on 2019-12-18 13:57

from django.db import migrations


def populate_OAIPMHEndpointSet(apps, schema_editor):
    OAIPMHEndpoint = apps.get_model('centre_registry', 'OAIPMHEndpoint')
    OAIPMHEndpointSet = apps.get_model('centre_registry', 'OAIPMHEndpointSet')

    for endpoint in OAIPMHEndpoint.objects.all():
        if OAIPMHEndpointSet.objects.filter(centre__pk=endpoint.centre.pk):
            endpoint_set = OAIPMHEndpointSet.objects.get(centre__pk=endpoint.centre.pk)
            endpoint_set.oaipmh_endpoints.add(endpoint)
        else:
            endpoint_set = OAIPMHEndpointSet(centre=endpoint.centre)
            endpoint_set.save()
            endpoint_set.oaipmh_endpoints.add(endpoint)
        endpoint_set.save()


class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0004_oaipmhendpointset'),
    ]

    operations = [
        migrations.RunPython(populate_OAIPMHEndpointSet),
    ]
