# Generated by Django 2.2.8 on 2020-01-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0005_populate_oaipmhendpointset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oaipmhendpointset',
            options={'ordering': ('centre',), 'verbose_name': 'OAI-PMH endpoints set', 'verbose_name_plural': 'OAI-PMH endpoints sets'},
        ),
        migrations.RemoveField(
            model_name='oaipmhendpoint',
            name='centre',
        ),
        migrations.AddField(
            model_name='oaipmhendpointset',
            name='note',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Additional note'),
        ),
    ]
