# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-18 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0019_remove_samlserviceprovider_information_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuedate', models.DateField(verbose_name=b'Assessment issued date (YYYY-MM-DD)')),
                ('duedate', models.DateField(verbose_name=b'Assessment due date (YYYY-MM-DD)')),
                ('type', models.ManyToManyField(to='centre_registry.CentreType', verbose_name=b'Type')),
            ],
            options={
                'ordering': ('issuedate', 'duedate'),
                'verbose_name': 'issue/due dates for a centre type',
                'verbose_name_plural': 'issue/due dates for a centre type',
            },
        ),
        migrations.AddField(
            model_name='centre',
            name='assessmentdates',
            field=models.ManyToManyField(blank=True, related_name='assessmentdates', to='centre_registry.AssessmentDates'),
        ),
    ]
