# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-11-27 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0020_auto_20170118_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentdates',
            name='duedate',
            field=models.DateField(verbose_name='Assessment due date (YYYY-MM-DD)'),
        ),
        migrations.AlterField(
            model_name='assessmentdates',
            name='issuedate',
            field=models.DateField(verbose_name='Assessment issued date (YYYY-MM-DD)'),
        ),
        migrations.AlterField(
            model_name='assessmentdates',
            name='type',
            field=models.ManyToManyField(to='centre_registry.CentreType', verbose_name='Type'),
        ),
    ]
