# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-12-02 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0021_auto_20191202_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samlserviceprovider',
            name='entity_id',
            field=models.CharField(max_length=1024, unique=True, verbose_name='Entity ID'),
        ),
        migrations.AlterField(
            model_name='samlserviceprovider',
            name='status_url',
            field=models.URLField(blank=True, max_length=1024, verbose_name='Status URL'),
        ),
    ]
