# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-12-05 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0022_auto_20191202_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmentdates',
            options={'ordering': ('issuedate', 'duedate'), 'verbose_name': 'issue/due dates for a centre administrative_contacttype', 'verbose_name_plural': 'issue/due dates for a centre type'},
        ),
    ]
