# Generated by Django 2.2.8 on 2020-02-07 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0025_auto_20200122_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oaipmhendpoint',
            name='metadata_format',
        ),
    ]
