# Generated by Django 2.2.8 on 2020-03-09 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('centre_registry', '0026_auto_20200306_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oaipmhendpoint',
            name='metadata_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='centre_registry.MetadataFormat', verbose_name='Metadata format (historic artifact)'),
        ),
        migrations.AlterField(
            model_name='oaipmhendpoint',
            name='web_services_type',
            field=models.CharField(max_length=8, verbose_name='Web services type (historic artifact)'),
        ),
        migrations.AlterField(
            model_name='oaipmhendpointset',
            name='set_type',
            field=models.CharField(max_length=1024, verbose_name='Set type'),
        ),
    ]
