# Generated by Django 2.2.8 on 2020-02-07 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0026_remove_oaipmhendpoint_metadataformat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MetadataFormat',
        ),
    ]
