# Generated by Django 2.2.8 on 2020-01-17 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0026_populate_oaipmhendpointset_20191218_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmentdates',
            options={'ordering': ('issuedate', 'duedate'), 'verbose_name': 'issue/due dates for a centre administrative_contacttype', 'verbose_name_plural': 'issue/due dates for a centre type'},
        ),
        migrations.AlterModelOptions(
            name='oaipmhendpointset',
            options={'ordering': ('centre',), 'verbose_name': 'OAI-PMH endpoints set', 'verbose_name_plural': 'OAI-PMH endpoints sets'},
        ),
        migrations.AlterField(
            model_name='centre',
            name='technical_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='technical_contact', to='centre_registry.Contact'),
        ),
        migrations.AlterField(
            model_name='oaipmhendpoint',
            name='metadata_format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='centre_registry.MetadataFormat', verbose_name='Metadata format (historic artifact)'),
        ),
    ]
