# Generated by Django 2.2.8 on 2020-03-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0027_auto_20200309_1842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oaipmhendpoint',
            options={'ordering': ('uri',), 'verbose_name': 'OAI-PMH Endpoint', 'verbose_name_plural': 'OAI-PMH Endpoints'},
        ),
        migrations.AlterModelOptions(
            name='oaipmhendpointset',
            options={'ordering': ('set_spec', 'set_type'), 'verbose_name': 'OAI-PMH Set', 'verbose_name_plural': 'OAI-PMH Sets'},
        ),
        migrations.AlterField(
            model_name='oaipmhendpoint',
            name='web_services_type',
            field=models.CharField(default='REST', max_length=8, verbose_name='Web services type (historic artifact)'),
        ),
    ]
