# Generated by Django 2.2.8 on 2020-03-06 17:35

from django.db import migrations


def create_oaipmh_sets(apps, schema_editor):
    OAIPMHEndpoint = apps.get_model("centre_registry", "OAIPMHEndpoint")
    OAIPMHEndpointSet = apps.get_model("centre_registndpoint_ry", "OAIPMHEndpointSet")
    unique_oaipmh_sets = {set_spec_type for set_spec_type in
                           list(OAIPMHEndpoint.objects.values_list("web_services_set", "web_services_type").distinct())}

    for unique_oaipmh_set in unique_oaipmh_sets:
        if unique_oaipmh_set["web_services_set"] == "":
            continue
        if unique_oaipmh_set["web_services_type"] == "":
            unique_oaipmh_set["web_services_type"] = "VLOSet"
        oaipmh_endpoit_set = OAIPMHEndpointSet(set_spec=unique_oaipmh_set["web_services_set"], set_type=unique_oaipmh_set["web_services_type"])
        oaipmh_endpoit_set.save()


def revert_create_oaipmh_sets(apps, schema_editor):
    OAIPMHEndpoint = apps.get_model("centre_registry", "OAIPMHEndpoint")
    OAIPMHEndpointSet = apps.get_model("centre_registry", "OAIPMHEndpointSet")

    for oaipmh_set in OAIPMHEndpointSet.objects.all():
        oaipmh_set.delete()


class Migration(migrations.Migration):
    dependencies = [
        ('centre_registry', '0028_auto_20200306_1701'),
    ]

    operations = [
        migrations.RunPython(create_oaipmh_sets, revert_create_oaipmh_sets),

    ]
