# Generated by Django 2.2.8 on 2020-02-18 12:28

from django.db import migrations


def populate_oaipmh_set(apps, schema_editor):
    OAIPMHEndpoint = apps.get_model("centre_registry", "OAIPMHEndpoint")
    OAIPMHEndpointSet = apps.get_model("centre_registndpoint_ry", "OAIPMHEndpointSet")
    unique_oaipmh_sets = {set_spec_type for set_spec_type in
                           list(OAIPMHEndpoint.objects.values_list("web_services_set", "web_services_type").distinct())}

    for unique_oaipmh_set in unique_oaipmh_sets:
        oaipmh_endpoit_set = OAIPMHEndpointSet(set_spec=unique_oaipmh_set["web_services_set"], set_type=unique_oaipmh_set["web_services_type"])
        oaipmh_endpoit_set.save()

def revert_populate_oaipmh_set(apps, schema_editor):
    OAIPMHEndpoint = apps.get_model("centre_registry", "OAIPMHEndpoint")
    OAIPMHEndpointSet = apps.get_model("centre_registry", "OAIPMHEndpointSet")

    for oaipmh_endpoint in OAIPMHEndpoint.objects.all():
        oaipmh_set = oaipmh_endpoint.oai_pmh_sets
        oaipmh_endpoint.web_services_set = oaipmh_set.set_spec
        oaipmh_endpoint.web_services_type = oaipmh_set.set_type
        oaipmh_set.oai_pmh_sets.remove(oaipmh_set)
        oaipmh_endpoint.save()






class Migration(migrations.Migration):
    dependencies = [
        ('centre_registry', '0028_auto_20200306_1701'),
    ]

    operations = [
        migrations.RunPython(populate_oaipmh_set, revert_populate_oaipmh_set),

    ]
