# Generated by Django 2.2.8 on 2020-02-13 20:23

import centre_registry.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0028_remove_metadataformat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oaipmhendpoint',
            name='uri_list',
        ),
        migrations.AlterField(
            model_name='oaipmhendpoint',
            name='web_services_set',
            field=centre_registry.fields.StringListField(help_text='Each URI should start from new line', null=True, verbose_name='List of base URIs'),
        ),
    ]
