# Generated by Django 2.2.8 on 2020-02-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0029_auto_20200218_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_service', models.CharField(max_length=1024, verbose_name='Web services')),
            ],
            options={
                'verbose_name': 'Web service',
                'verbose_name_plural': 'Web services',
                'ordering': ('web_service',),
            },
        ),
    ]
