# Generated by Django 2.2.8 on 2020-02-13 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0029_auto_20200213_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oaipmhendpoint',
            name='web_services_type',
        ),
    ]
