# Generated by Django 2.2.8 on 2020-03-06 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0030_oaipmh_endpoint_manytomany_oaipmh_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oaipmhendpoint',
            name='web_services_set',
        ),
        migrations.RemoveField(
            model_name='oaipmhendpoint',
            name='web_services_type',
        ),
    ]
