# Generated by Django 2.2.8 on 2020-04-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0030_oaipmh_endpoint_manytomany_oaipmh_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oaipmhendpointset',
            name='set_spec',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Set specification'),
        ),
        migrations.AlterField(
            model_name='oaipmhendpointset',
            name='set_type',
            field=models.CharField(default='VLOSet', max_length=1024, verbose_name='Set type'),
        ),
    ]
