# Generated by Django 2.2.8 on 2020-04-09 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0031_auto_20200409_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oaipmhendpoint',
            name='metadata_format',
        ),
        migrations.RemoveField(
            model_name='oaipmhendpoint',
            name='web_services_set',
        ),
        migrations.RemoveField(
            model_name='oaipmhendpoint',
            name='web_services_type',
        ),
        migrations.DeleteModel(
            name='MetadataFormat',
        ),
    ]
