# Generated by Django 4.2.4 on 2023-08-17 12:09

import centre_registry.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0032_auto_20200409_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=100, verbose_name='Organisation')),
                ('institution', models.CharField(blank=True, max_length=200, verbose_name='Institution')),
                ('working_unit', models.CharField(blank=True, max_length=200, verbose_name='Working unit')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Postal code')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('latitude', models.CharField(max_length=20, validators=[centre_registry.models.validate_latitude], verbose_name='Latitude (from e.g. Google Maps)')),
                ('longitude', models.CharField(max_length=20, validators=[centre_registry.models.validate_longitude], verbose_name='Longitude (from e.g. Google Maps)')),
            ],
            options={
                'verbose_name': 'organisation',
                'verbose_name_plural': 'organisations',
                'ordering': ('organisation_name',),
            },
        ),
    ]
