# Generated by Django 4.1.7 on 2023-04-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0032_auto_20200409_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=100, verbose_name='Organisation')),
                ('institution', models.CharField(blank=True, max_length=200, verbose_name='Institution')),
                ('working_unit', models.CharField(blank=True, max_length=200, verbose_name='Working unit')),
            ],
            options={
                'verbose_name': 'organisation',
                'verbose_name_plural': 'organisations',
                'ordering': ('organisation_name',),
            },
        ),
    ]
