# Generated by Django 2.2.8 on 2020-02-20 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0033_populate_manytomany'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oaipmhendpoint',
            name='web_services_set',
        ),
    ]
