# Generated by Django 4.2.4 on 2023-08-17 13:59

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0033_organisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='KCentre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audiences', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None, verbose_name='Audience list')),
                ('competence', models.CharField(max_length=2000, verbose_name='Competence description')),
                ('data_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None, verbose_name='Data types')),
                ('generic_topics', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None, verbose_name='Generic topics')),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None, verbose_name='Keywords')),
                ('language_processing_spec', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None, verbose_name='Language processing specifics')),
                ('linguistic_topics', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None, verbose_name='Linguistic topics')),
                ('pid', models.URLField(unique=True, verbose_name='PID')),
                ('tour_de_clarin_interview', models.URLField(verbose_name='TdC interview URL')),
                ('tour_de_clarin_intro', models.URLField(verbose_name='TdC intro URL')),
                ('website_language', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None, verbose_name='Website language')),
                ('centre_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='centre', to='centre_registry.centre')),
            ],
            options={
                'verbose_name': 'k-centre',
                'verbose_name_plural': 'k-centres',
            },
        ),
        migrations.CreateModel(
            name='KCentreServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=200, unique=True, verbose_name='KCentre service type')),
            ],
            options={
                'verbose_name': 'Service type',
                'verbose_name_plural': 'Service types',
            },
        ),
        migrations.CreateModel(
            name='KCentreStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, unique=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'KCentre status',
                'verbose_name_plural': 'KCentre statuses',
            },
        ),
        migrations.CreateModel(
            name='ResourceFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_family', models.CharField(max_length=200, unique=True, verbose_name='Resource family')),
            ],
            options={
                'verbose_name': 'Resource family',
                'verbose_name_plural': 'Resource families',
            },
        ),
        migrations.CreateModel(
            name='KCentreFormQueue',
            fields=[
                ('kcentre_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='centre_registry.kcentre')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='Form submission date')),
                ('review_date', models.DateTimeField(blank=True, null=True, verbose_name='Form review date')),
                ('comment', models.CharField(max_length=2000, verbose_name='Comment')),
            ],
            bases=('centre_registry.kcentre',),
        ),
        migrations.AddField(
            model_name='kcentre',
            name='resource_families_fks',
            field=models.ManyToManyField(related_name='resource_families', to='centre_registry.resourcefamily'),
        ),
        migrations.AddField(
            model_name='kcentre',
            name='secondary_hosts_fks',
            field=models.ManyToManyField(related_name='secondary_hosts', to='centre_registry.organisation'),
        ),
        migrations.AddField(
            model_name='kcentre',
            name='service_type_fk',
            field=models.ManyToManyField(related_name='service_types', to='centre_registry.kcentreservicetype'),
        ),
        migrations.AddField(
            model_name='kcentre',
            name='status_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kcentre_status', to='centre_registry.kcentrestatus'),
        ),
    ]
