# Generated by Django 4.1.7 on 2023-04-17 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0033_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='centre',
            name='organisation_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='centre_registry.organisation'),
        ),
    ]
