# Generated by Django 2.2.8 on 2020-02-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0033_populate_manytomany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webservice',
            name='web_service',
            field=models.CharField(max_length=1024, verbose_name='Web service'),
        ),
    ]
