# Generated by Django 2.2.8 on 2020-02-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0034_auto_20200221_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oaipmhendpoint',
            name='web_services_set',
        ),
        migrations.AlterField(
            model_name='webservice',
            name='web_service',
            field=models.CharField(max_length=1024, unique=True, verbose_name='Web service'),
        ),
    ]
