# Generated by Django 4.1.7 on 2023-04-17 15:04

from django.db import migrations, models
import django.db.models.deletion


def forwards(apps, schema_editor):
    # CentreModel and OrganisationModel are types, therefore CamelCase
    CentreModel = apps.get_model("centre_registry", "Centre")
    OrganisationModel = apps.get_model("centre_registry", "Organisation")
    for centre_object in CentreModel.objects.all():
        organisation_name = centre_object.organisation_name
        institution = centre_object.institution
        working_unit = centre_object.working_unit

        organisation_object = OrganisationModel(organisation_name=organisation_name,
                                                institution=institution,
                                                working_unit=working_unit)
        organisation_id = organisation_object.id
        centre_object.organisation_fk = organisation_id

        organisation_object.save()
        centre_object.save()


class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0034_centre_organisation_fk'),
    ]

    operations = [
        migrations.RunPython(forwards)
    ]
