# Generated by Django 4.1.7 on 2023-04-20 10:51

from django.db import migrations, models
import django.db.models.deletion
import djangoarrayfield.fields
import djangoarrayfield.serializers


class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0034_populate_organisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='KCentreServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=200, unique=True, verbose_name='KCentre service type')),
            ],
            options={
                'verbose_name': 'Service type',
                'verbose_name_plural': 'Service types',
            },
        ),
        migrations.CreateModel(
            name='KCentreStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, unique=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'KCentre status',
                'verbose_name_plural': 'KCentre statutes',
            },
        ),
        migrations.CreateModel(
            name='ResourceFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_family', models.CharField(max_length=200, unique=True, verbose_name='Resource family')),
            ],
            options={
                'verbose_name': 'Resource family',
                'verbose_name_plural': 'Resource families',
            },
        ),
        migrations.RemoveField(
            model_name='centre',
            name='address',
        ),
        migrations.RemoveField(
            model_name='centre',
            name='city',
        ),
        migrations.RemoveField(
            model_name='centre',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='centre',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='centre',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='centre',
            name='organisation_name',
        ),
        migrations.RemoveField(
            model_name='centre',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='centre',
            name='working_unit',
        ),
        migrations.CreateModel(
            name='KCentre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audiences', djangoarrayfield.fields.DjangoArrayField(decoder=djangoarrayfield.serializers.DjangoArrayDecoder, encoder=djangoarrayfield.serializers.DjangoArrayEncoder, verbose_name='Audience list')),
                ('competence', models.CharField(max_length=2000, verbose_name='Competence description')),
                ('data_types', djangoarrayfield.fields.DjangoArrayField(decoder=djangoarrayfield.serializers.DjangoArrayDecoder, encoder=djangoarrayfield.serializers.DjangoArrayEncoder, verbose_name='Data types')),
                ('generic_topics', djangoarrayfield.fields.DjangoArrayField(decoder=djangoarrayfield.serializers.DjangoArrayDecoder, encoder=djangoarrayfield.serializers.DjangoArrayEncoder, verbose_name='Generic topics')),
                ('keywords', djangoarrayfield.fields.DjangoArrayField(decoder=djangoarrayfield.serializers.DjangoArrayDecoder, encoder=djangoarrayfield.serializers.DjangoArrayEncoder, verbose_name='Keywords')),
                ('language_processing_spec', djangoarrayfield.fields.DjangoArrayField(decoder=djangoarrayfield.serializers.DjangoArrayDecoder, encoder=djangoarrayfield.serializers.DjangoArrayEncoder, verbose_name='Language processing specifics')),
                ('linguistic_topics', djangoarrayfield.fields.DjangoArrayField(decoder=djangoarrayfield.serializers.DjangoArrayDecoder, encoder=djangoarrayfield.serializers.DjangoArrayEncoder, verbose_name='Linguistic topics')),
                ('pid', models.URLField(unique=True, verbose_name='PID')),
                ('tour_de_clarin_interview', models.URLField(verbose_name='TdC interview URL')),
                ('tour_de_clarin_intro', models.URLField(verbose_name='TdC intro URL')),
                ('website_language', djangoarrayfield.fields.DjangoArrayField(decoder=djangoarrayfield.serializers.DjangoArrayDecoder, encoder=djangoarrayfield.serializers.DjangoArrayEncoder, verbose_name='Website language')),
                ('centre_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='centre', to='centre_registry.centre')),
                ('resource_families_fks', models.ManyToManyField(related_name='resource_families', to='centre_registry.resourcefamily')),
                ('secondary_hosts_fks', models.ManyToManyField(related_name='secondary_hosts', to='centre_registry.organisation')),
                ('service_type_fk', models.ManyToManyField(related_name='service_types', to='centre_registry.kcentreservicetype')),
                ('status_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kcentre_status', to='centre_registry.kcentrestatus')),
            ],
            options={
                'verbose_name': 'k-centre',
                'verbose_name_plural': 'k-centres',
            },
        ),
    ]
