# Generated by Django 2.2.8 on 2020-02-26 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0035_auto_20200225_1226'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WebService',
            new_name='WebServiceSet',
        ),
    ]
