# Generated by Django 4.2.18 on 2025-01-29 15:20

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0036_remove_centre_institution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centre',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='historicalcentre',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='Country'),
        ),
    ]
