# Generated by Django 4.2.7 on 2023-11-23 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0036_kcentres_db_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShadowCentre',
            fields=[
                ('centre_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='centre_registry.centre')),
            ],
            bases=('centre_registry.centre',),
        ),
        migrations.CreateModel(
            name='ShadowKCentre',
            fields=[
                ('kcentre_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='centre_registry.kcentre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=False)),
                ('kcentre_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shadow_kcentre', to='centre_registry.kcentre')),
                ('shadow_centre_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shadow_kcentre', to='centre_registry.shadowcentre')),
            ],
            bases=('centre_registry.kcentre',),
        ),
        migrations.CreateModel(
            name='ShadowKCentreServiceType',
            fields=[
                ('kcentreservicetype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='centre_registry.kcentreservicetype')),
                ('kcentre_service_type_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shadow', to='centre_registry.kcentreservicetype')),
            ],
            bases=('centre_registry.kcentreservicetype',),
        ),
        migrations.CreateModel(
            name='ShadowKCentreStatus',
            fields=[
                ('kcentrestatus_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='centre_registry.kcentrestatus')),
                ('kcentre_status_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shadow', to='centre_registry.kcentrestatus')),
            ],
            bases=('centre_registry.kcentrestatus',),
        ),
        migrations.CreateModel(
            name='ShadowOrganisation',
            fields=[
                ('organisation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='centre_registry.organisation')),
                ('organisation_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shadow', to='centre_registry.organisation')),
            ],
            bases=('centre_registry.organisation',),
        ),
        migrations.AddField(
            model_name='centre',
            name='organisation_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='centre_registry.organisation'),
        ),
        migrations.AddField(
            model_name='shadowkcentre',
            name='shadow_kcentre_service_type_fks',
            field=models.ManyToManyField(related_name='shadow_kcentre', to='centre_registry.shadowkcentreservicetype'),
        ),
        migrations.AddField(
            model_name='shadowkcentre',
            name='shadow_kcentre_status_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centre_registry.shadowkcentrestatus'),
        ),
        migrations.AddField(
            model_name='shadowkcentre',
            name='shadow_resource_families_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shadow_kcentre', to='centre_registry.resourcefamily'),
        ),
        migrations.AddField(
            model_name='shadowkcentre',
            name='shadow_secondary_host_fk',
            field=models.ManyToManyField(blank=True, null=True, to='centre_registry.shadoworganisation'),
        ),
        migrations.AddField(
            model_name='shadowcentre',
            name='shadow_organisation_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shadow', to='centre_registry.centre'),
        ),
    ]