# Generated by Django 2.2.8 on 2020-02-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0036_auto_20200226_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='webserviceset',
            name='type',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='webserviceset',
            name='web_service',
            field=models.CharField(max_length=1024, verbose_name='Web service'),
        ),
    ]
