# Generated by Django 4.2.18 on 2025-03-05 10:00

import centre_registry.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import simple_history.models

from centre_registry.models import Centre
from centre_registry.models import CertificationStatus
from centre_registry.models import TypeCertificationStatus

import logging


def populate_certification_status(apps, schema):
    centres = Centre.objects.all()

    logging.critical("TRIES TO POPULATE CERTIFICATION STATUS")

    if not CertificationStatus.objects.filter(status='Certified').exists():
        CERTIFIED = CertificationStatus(status='Certified')
        CERTIFIED.save()
    else:
        CERTIFIED = CertificationStatus.objects.get(status='Certified')

    if not CertificationStatus.objects.filter(status='Pending').exists():
        PENDING = CertificationStatus(status='Pending')
        PENDING.save()
    else:
        PENDING = CertificationStatus.objects.get(status='Pending')

    if not CertificationStatus.objects.filter(status='Pending (recertification)').exists():
        PENDING_RECERTIFICATION = CertificationStatus(status='Pending (recertification)')
        PENDING_RECERTIFICATION.save()
    else:
        PENDING_RECERTIFICATION = CertificationStatus.objects.get(status='Pending (recertification)')

    if not CertificationStatus.objects.filter(status='Suspended').exists():
        SUSPENDED = CertificationStatus(status='Suspended')
        SUSPENDED.save()
    else:
        SUSPENDED = CertificationStatus.objects.get(status='Suspended')

    if not CertificationStatus.objects.filter(status='Archived').exists():
        ARCHIVED = CertificationStatus(status='Archived')
        ARCHIVED.save()
    else:
        ARCHIVED = CertificationStatus.objects.get(status='Archived')

    if not CertificationStatus.objects.filter(status='Placeholder').exists():
        PLACEHOLDER = CertificationStatus(status='Placeholder')
        PLACEHOLDER.save()
    else:
        PLACEHOLDER = CertificationStatus.objects.get(status='Placeholder')

    for centre in centres:
        logging.critical("ITERATES OVER CENTRES")
        assessment_dates = centre.assessmentdates.all()
        centre_types = centre.centre_type.all()
        status_comment = centre.type_status_comment
        if "certified" in status_comment or 'Certified' in status_comment:
            certification_status = CERTIFIED
        elif "expired" in status_comment or "Expired" in status_comment:
            certification_status = PENDING_RECERTIFICATION
        elif "suspended" in status_comment or "Suspended" in status_comment:
            certification_status = SUSPENDED
        elif "pending" in status_comment or "Pending" in status_comment:
            certification_status = PENDING
        elif "archived" in status_comment or "Archived" in status_comment:
            certification_status = ARCHIVED
        else:
            certification_status = PLACEHOLDER
        logging.critical("THIS IS CERTIFICATION STATUS")
        logging.critical(certification_status)

        for assessment_date in assessment_dates:
            centre_type = assessment_date.type.all()[0]
            centre_type_certification_status = TypeCertificationStatus(assessmentdate=assessment_date,
                                                                       certification_status=certification_status,
                                                                       type_status_comment=status_comment,
                                                                       centre_type=centre_type,
                                                                       type_certificate_url=centre.type_certificate_url)

            centre_type_certification_status.save()
            centre.type_certification_status_fk.add(centre_type_certification_status)
        centre.save()


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('centre_registry', '0036_certificationstatus_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_certification_status),
    ]

