# Generated by Django 4.2.17 on 2025-01-29 13:46

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0036_remove_centre_institution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centre',
            name='country_code',
            field=django_countries.fields.CountryField(max_length=2, null=True, verbose_name='Country code'),
        ),
        migrations.AddField(
            model_name='historicalcentre',
            name='country_code',
            field=django_countries.fields.CountryField(max_length=2, null=True, verbose_name='Country code'),
        ),
    ]
