# Generated by Django 4.2.24 on 2025-09-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0037_populate_certification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centre',
            name='centre_type',
            field=models.ManyToManyField(related_name='centres_of_type', to='centre_registry.centretype', verbose_name='Centre types'),
        ),
    ]
