# Generated by Django 2.2.8 on 2020-02-26 19:15

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('centre_registry', '0037_auto_20200226_2146'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WebServiceSet',
            new_name='WebServiceSetSpec',
        ),
        migrations.AlterModelOptions(
            name='webservicesetspec',
            options={'ordering': ('web_service',), 'verbose_name': 'Web service specification', 'verbose_name_plural': 'Web service specifications'},
        ),
        migrations.RenameField(
            model_name='webservicesetspec',
            old_name='type',
            new_name='service_type',
        ),
    ]
