# Generated by Django 4.2.20 on 2025-03-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0037_populate_certification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centre',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalcentre',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
