# Generated by Django 4.2.18 on 2025-01-29 16:24

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0037_centre_country_historicalcentre_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='consortium',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='historicalconsortium',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='Country'),
        ),
    ]
