# Generated by Django 4.2.20 on 2025-04-03 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('centre_registry', '0038_alter_centre_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centre',
            name='assessmentdates',
            field=models.ManyToManyField(blank=True, related_name='assessmentdates_old', to='centre_registry.assessmentdates'),
        ),
        migrations.AlterField(
            model_name='centre',
            name='type',
            field=models.ManyToManyField(related_name='centres_of_type_old', to='centre_registry.centretype', verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='TypeCertificationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_status_comment', models.CharField(blank=True, max_length=100, verbose_name="Comments about centre's type")),
                ('requires_manual_review', models.BooleanField(default=False, verbose_name='Is certification out of date')),
                ('assessmentdate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessmentdate', to='centre_registry.assessmentdates')),
                ('certification_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='centre_registry.certificationstatus')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='centres_of_type', to='centre_registry.centretype', verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalTypeCertificationStatus',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('type_status_comment', models.CharField(blank=True, max_length=100, verbose_name="Comments about centre's type")),
                ('requires_manual_review', models.BooleanField(default=False, verbose_name='Is certification out of date')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('assessmentdate', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='centre_registry.assessmentdates')),
                ('certification_status', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='centre_registry.certificationstatus')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='centre_registry.centretype', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'historical type certification status',
                'verbose_name_plural': 'historical type certification statuss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
