# Generated by Django 2.2.8 on 2020-02-26 19:17

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('centre_registry', '0038_auto_20200226_2215'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WebServiceSetSpec',
            new_name='OAIPMHEndpointSpec',
        ),
    ]
