# Generated by Django 4.1.7 on 2023-04-17 15:04

from django.db import migrations


def forwards(apps, schema_editor):
    # CentreModel and OrganisationModel are classes, therefore CamelCase
    ConsortiumModel = apps.get_model("centre_registry", "Consortium")

    for consortium_object in ConsortiumModel.objects.all():
        country_code = consortium_object.country_code
        consortium_object.country = country_code
        consortium_object.save()


class Migration(migrations.Migration):
    dependencies = [
        ('centre_registry', '0038_consortium_country_historicalconsortium_country'),
    ]

    operations = [
        migrations.RunPython(forwards)
    ]
