# Generated by Django 2.2.8 on 2020-02-26 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0039_auto_20200226_2217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oaipmhendpointspec',
            options={'ordering': ('web_service', 'service_type'), 'verbose_name': 'OAI-PMH endpoint specification', 'verbose_name_plural': 'OAI-PMH endpoint specifications'},
        ),
    ]
