# Generated by Django 4.2.20 on 2025-04-03 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0039_alter_centre_assessmentdates_alter_centre_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centre',
            name='type_certification_status_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='centre_registry.typecertificationstatus'),
        ),
        migrations.AddField(
            model_name='historicalcentre',
            name='type_certification_status_new',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='centre_registry.typecertificationstatus'),
        ),
    ]
