# Generated by Django 4.2.18 on 2025-02-12 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0039_populate_consortium_country_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='centre',
            old_name='type_status',
            new_name='type_status_comment',
        ),
        migrations.RenameField(
            model_name='historicalcentre',
            old_name='type_status',
            new_name='type_status_comment',
        ),
    ]
