# Generated by Django 4.2.20 on 2025-04-03 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


from centre_registry.models import AssessmentDates
from centre_registry.models import Centre
from centre_registry.models import CentreType
from centre_registry.models import CertificationStatus
from centre_registry.models import TypeCertificationStatus


def populate_type_certification_status(apps, schema):
    centres = Centre.objects.all()
    for centre in centres:
        assessment_dates = centre.assessmentdates
        centre_types = centre.centre_type
        certification_status = centre.type_certification_status
        status_comment = centre.type_status_comment
        for assessment_date, centre_type in list(zip(assessment_dates, centre_types)):
            type_certification_status = TypeCertificationStatus(type=centre_types, assessmentdate=assessment_date, centre=centre,
                                    status=certification_status, type_status_comment=status_comment)
            type_certification_status.save()
            centre.type_certification_status_new = type_certification_status
            centre.save()


class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0040_centre_type_certification_status_new_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_type_certification_status),
    ]