# Generated by Django 2.2.8 on 2020-02-26 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0040_auto_20200226_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oaipmhendpoint',
            old_name='web_services',
            new_name='specifications',
        ),
    ]
