# Generated by Django 2.2.8 on 2020-02-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0041_auto_20200226_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oaipmhendpointspec',
            name='service_type',
            field=models.CharField(max_length=1024, null=True, verbose_name='Type'),
        ),
    ]
