# Generated by Django 2.2.8 on 2020-02-27 14:08

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('centre_registry', '0042_auto_20200226_2258'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OAIPMHEndpointSpec',
            new_name='OAIPMHEndpointSet',
        ),
    ]
