# Generated by Django 4.2.20 on 2025-04-07 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0043_remove_centre_type_certification_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltypecertificationstatus',
            name='type',
        ),
        migrations.RemoveField(
            model_name='typecertificationstatus',
            name='type',
        ),
    ]
