# Generated by Django 2.2.8 on 2020-02-27 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0043_auto_20200227_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oaipmhendpointset',
            options={'ordering': (), 'verbose_name': 'OAI-PMH endpoint specification', 'verbose_name_plural': 'OAI-PMH endpoint specifications'},
        ),
    ]
