# Generated by Django 2.2.8 on 2020-02-27 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0044_auto_20200227_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oaipmhendpointset',
            old_name='web_service',
            new_name='set_spec',
        ),
        migrations.RenameField(
            model_name='oaipmhendpointset',
            old_name='service_type',
            new_name='set_type',
        ),
    ]
