# Generated by Django 4.2.20 on 2025-04-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0044_remove_historicaltypecertificationstatus_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltypecertificationstatus',
            name='type_certificate_url',
            field=models.URLField(blank=True, max_length=2000, verbose_name='Centre type certificate URL'),
        ),
        migrations.AddField(
            model_name='typecertificationstatus',
            name='type_certificate_url',
            field=models.URLField(blank=True, max_length=2000, verbose_name='Centre type certificate URL'),
        ),
    ]
