# Generated by Django 2.2.8 on 2020-02-27 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0045_auto_20200227_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oaipmhendpointset',
            options={'ordering': ('set_spec', 'set_type'), 'verbose_name': 'OAI-PMH endpoint specification', 'verbose_name_plural': 'OAI-PMH endpoint specifications'},
        ),
        migrations.RenameField(
            model_name='oaipmhendpoint',
            old_name='specifications',
            new_name='oai_pmh_sets',
        ),
    ]
