# Generated by Django 4.2.28 on 2026-02-19 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0046_populate_certification_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmentdates',
            options={'ordering': ('issuedate', 'duedate'), 'verbose_name': 'issue/due date for a centre type', 'verbose_name_plural': 'issue/due dates for a centre type'},
        ),
        migrations.AlterModelOptions(
            name='certificationstatus',
            options={'ordering': ('status',), 'verbose_name': 'Certification Status', 'verbose_name_plural': 'Certification Statuses'},
        ),
        migrations.AlterModelOptions(
            name='historicalassessmentdates',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical issue/due date for a centre type', 'verbose_name_plural': 'historical issue/due dates for a centre type'},
        ),
        migrations.AlterModelOptions(
            name='historicalcertificationstatus',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Certification Status', 'verbose_name_plural': 'historical Certification Statuses'},
        ),
        migrations.AlterModelOptions(
            name='historicaltypecertificationstatus',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical type certification status', 'verbose_name_plural': 'historical type certification statuses'},
        ),
        migrations.AlterModelOptions(
            name='typecertificationstatus',
            options={'verbose_name': 'type certification status', 'verbose_name_plural': 'type certification statuses'},
        ),
    ]
