# Generated by Django 4.2.20 on 2025-05-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0046_populate_certification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centre',
            name='type_certification_status_fk',
            field=models.ManyToManyField(related_name='type_certification', to='centre_registry.typecertificationstatus'),
        ),
    ]
