# Generated by Django 4.2.28 on 2026-02-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0047_alter_assessmentdates_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centre',
            name='type_certification_status_fk',
            field=models.ManyToManyField(blank=True, related_name='type_certification', to='centre_registry.typecertificationstatus'),
        ),
    ]
