# Generated by Django 4.2.28 on 2026-04-09 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0048_alter_centre_type_certification_status_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centre',
            name='consortium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consortiums_centre', to='centre_registry.consortium'),
        ),
    ]
