# Generated by Django 4.2.28 on 2026-02-26 15:02

from django.db import migrations, models


def forwards(apps, schema_editor):
    ConsortiaModel = apps.get_model('centre_registry', 'Consortium')
    for consortium in ConsortiaModel.objects.all():
        if consortium.country_code is not None:
            consortium.country = consortium.country_code
            consortium.save()

class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0049_alter_centre_type_certification_status_fk,'),
    ]

    operations = [
        migrations.RunPython(forwards)
    ]
