# Generated by Django 4.2.28 on 2026-07-29 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0050_populate_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='centre',
            old_name='type_status_comment',
            new_name='type_status',
        ),
        migrations.RenameField(
            model_name='historicalcentre',
            old_name='type_status_comment',
            new_name='type_status',
        ),
    ]
