# Generated by Django 4.2.28 on 2026-08-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0051_rename_type_status_comment_centre_type_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centre',
            name='type_certification_status_fk',
        ),
        migrations.AddField(
            model_name='centre',
            name='type_certification_status_fks',
            field=models.ManyToManyField(blank=True, related_name='certified_centre', to='centre_registry.typecertificationstatus'),
        ),
    ]
