# Generated by Django 4.2.28 on 2026-07-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre_registry', '0051_rename_type_status_comment_centre_type_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='centre',
            old_name='type_certification_status_fk',
            new_name='type_certification_status_fks',
        ),
        migrations.RenameField(
            model_name='historicalcentre',
            old_name='type_certification_status_fk',
            new_name='type_certification_status_fks',
        ),
    ]

